compressionLevel: mixed

enableGlobalCache: false

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs

packageExtensions:
  "eslint-plugin-prettier@*":
    dependencies:
      "prettier": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
